

services:

  # Database to store XML data
  db-xml:
    container_name: db-xml
    build: images/db/xml
    volumes:
      - xml-data:/var/lib/postgresql/shared-data/
    ports:
      - "${EXP_PORT_PG_XML}:5432"

  # Database to store Relational data
  db-rel:
    container_name: db-rel
    build: images/db/rel
    volumes:
      - rel-data:/var/lib/postgresql/shared-data/
    ports:
      - "${EXP_PORT_PG_REL}:5432"

  # Container that automatically converts CSV to XML and then imports the XML to db-xml
  importer:
    container_name: importer
    build: images/python
    volumes:
      - ./src/daemon/importer:/usr/src/app
      - ./volumes/shared:/shared
      - ./volumes/csv:/csv
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
    depends_on:
      - db-xml

  # Container that automatically migrates data from db-xml to db-rel
  migrator:
    container_name: migrator
    build: images/python
    volumes:
      - ./src/daemon/migrator:/usr/src/app
      - ./volumes/shared:/shared
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      POLLING_FREQ: ${POLLING_FREQ}
    depends_on:
      - db-xml
      - db-rel

  # Container that automatically migrates data from db-xml to db-rel
  gis-updater:
    container_name: gis-updater
    build: images/python
    volumes:
      - ./src/daemon/gis-updater:/usr/src/app
      - ./volumes/shared:/shared
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      POLLING_FREQ: ${POLLING_FREQ}
      ENTITIES_PER_ITERATION: ${ENTITIES_PER_ITERATION}
    depends_on:
      - api-gis
      - api-entities

  # Container that runs the RPC server
  rpc-server:
    container_name: rpc-server
    build: images/python
    volumes:
      - ./src/server/rpc:/usr/src/app
      - ./volumes/shared:/shared
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      RPC_SERVER_PORT: ${RPC_SERVER_PORT}
    depends_on:
      - db-xml

  # Container that runs the web interface for displaying entities
  frontend-ent:
    container_name: frontend-ent
    build: images/web
    volumes:
      - ./src/frontend/ent:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_FRONTEND_ENT}:${EXT_PORT_FRONTEND_ENT}"
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      WEB_PORT: ${EXT_PORT_FRONTEND_ENT}
      API_ENTITIES_URL: "api-entities:${API_PORT}"
    depends_on:
      - api-entities

  # Container that runs the web interface for displaying the map
  frontend-gis:
    container_name: frontend-gis
    build: images/web
    volumes:
      - ./src/frontend/gis:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_FRONTEND_GIS}:${EXT_PORT_FRONTEND_GIS}"
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      WEB_PORT: ${EXT_PORT_FRONTEND_GIS}
      API_GIS_URL: "api-gis:${API_PORT}"
    depends_on:
      - api-gis

  # Container that runs the web interface for displaying the map
  frontend-proc:
    container_name: frontend-proc
    build: images/web
    volumes:
      - ./src/frontend/proc:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_FRONTEND_PROC}:${EXT_PORT_FRONTEND_PROC}"
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      WEB_PORT: ${EXT_PORT_FRONTEND_PROC}
      API_GRAPHQL_URL: "api-graphql:${API_PORT}"
      API_PROC_URL: "api-proc:${API_PORT}"
    depends_on:
      - api-proc
      - api-graphql

  # Container that runs the API for entities
  api-entities:
    container_name: api-entities
    build: images/python
    volumes:
      - ./src/api/entities:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_API_ENTITIES}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}

  # Container that runs the API for gis
  api-gis:
    container_name: api-gis
    build: images/python
    volumes:
      - ./src/api/gis:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_API_GIS}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}

  # Container that runs the API for procedures
  api-proc:
    container_name: api-proc
    build: images/python
    volumes:
      - ./src/api/proc:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_API_PROC}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}

  # Container that runs the API for graphql
  api-graphql:
    container_name: api-graphql
    build: images/python
    volumes:
      - ./src/api/graphql:/usr/src/app
      - ./volumes/shared:/shared
    ports:
      - "${EXT_PORT_API_GRAPHQL}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}

volumes:
  xml-data:
  rel-data:
